### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by corrpel** [mancuniancol/plugin.video.rarbg#1]
Sort view by seeders.
To have a better understanding, go to rarBG, select movies/x264/1080p then sort by seeders.
This way we will be able to watch for the best content in the moment.
Thank you.

**Comment by mancuniancol** [comment]
I will add some documentation soon.  But, I left the default sorting of the torrentapi which is last add.

I've added in the search the option of different sorting, though.

In your case, you need to search with an empty query and it will search for all the movies available, but you can sort them in the way that you like better.

If you use last, you will get the same result from the main menu.

Please, be sure that you are using version 1.0.1.

I will close this issue, because I won't add the sorting option in the main menu.
